title: "Non‑Stationarity in RL"
description: "Poster companion: adapting RL to evolving environments."
url: "https://<your-username>.github.io"
baseurl: "/<your-repo-name>" # project site: repo name prefixed with /


# Theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme


# Socials (optional)
author:
name: "Ali Najar & Mazdak Teymourian"
email: "anajar13750@gmail.com"


# Markdown + syntax
markdown: kramdown
kramdown:
input: GFM
math_engine: mathjax


# Collections (future-proofing if you add more posts/pages)
collections:
posts:
output: true


# Defaults (adds custom CSS + MathJax to all pages)
defaults:
- scope:
path: ""
values:
layout: default
# Include custom CSS in the head via theme hook
include:
- assets/css/custom.css